hmLoadTopic({
hmKeywords:"",
hmTitle:"Data link capability",
hmDescription:"The HsM system can also manage pure analog dispensers (with no data link to the HsM HsM Backend), this device filter term type can be used to filter devices by their capability...",
hmPrevLink:"compound-device-status.html",
hmNextLink:"device-dates.html",
hmParentLink:"device-filter-term-types.html",
hmBreadCrumbs:"<a href=\"backend-infrastructure.html\">Backend infrastructure<\/a> &gt; <a href=\"client-service.html\">Client Service<\/a> &gt; <a href=\"device-filter.html\">Device filter<\/a> &gt; <a href=\"device-filter-term-types.html\">Device filter term types<\/a>",
hmTitlePath:"Backend infrastructure > Client Service > Device filter > Device filter term types > Data link",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Data link capability<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">The HsM system can also manage pure analog dispensers (with no data link to the HsM HsM Backend), this device filter term type can be used to filter devices by their capability to send data to the HsM &lt;%BACKEND%.<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Settings<\/span><\/h1>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0.3750rem 0;\"><table style=\"border:none; border-spacing:0;\">\n\r<thead>\n\r<tr>\n\r<th style=\"vertical-align:top; width:11.0625rem; padding:0; border:none\"><p class=\"p_Normal\">Setting<\/p>\n\r<\/th>\n\r<th style=\"vertical-align:top; width:31.8125rem; padding:0; border:none\"><p class=\"p_Normal\">Description<\/p>\n\r<\/th>\n\r<\/tr>\n\r<\/thead>\n\r<tbody>\n\r<tr>\n\r<td style=\"vertical-align:top; width:11.0625rem; padding:0; border:none\"><p class=\"p_Normal\">Capability filter<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:31.8125rem; padding:0; border:none\"><p class=\"p_Normal\">Yes: Filters for devices that can communicate with the HsM backend. <\/p>\n\r<p class=\"p_Normal\">No: Filters for devices that cannot communicate with the HsM backend.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:11.0625rem; padding:0; border:none\"><p class=\"p_Normal\">Compound member handling<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:31.8125rem; padding:0; border:none\"><p class=\"p_Normal\">Include Devices with compound members that have data link capability<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/tbody>\n\r<\/table>\n\r<\/div>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Validation rules<\/span><\/h1>\n\r<p class=\"p_Normal\">None<\/p>\n\r"
})
