hmLoadTopic({
hmKeywords:"",
hmTitle:"Device type",
hmDescription:"Filters for devices that are of one of the given device types.",
hmPrevLink:"device-dates_2.html",
hmNextLink:"latest-status-update.html",
hmParentLink:"device-filter-term-types.html",
hmBreadCrumbs:"<a href=\"backend-infrastructure.html\">Backend infrastructure<\/a> &gt; <a href=\"client-service.html\">Client Service<\/a> &gt; <a href=\"device-filter.html\">Device filter<\/a> &gt; <a href=\"device-filter-term-types.html\">Device filter term types<\/a>",
hmTitlePath:"Backend infrastructure > Client Service > Device filter > Device filter term types > Device type",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Device type<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Filters for devices that are of one of the given device types.<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Settings<\/span><\/h1>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0.3750rem 0;\"><table style=\"border:none; border-spacing:0;\">\n\r<thead>\n\r<tr>\n\r<th style=\"vertical-align:top; width:11.0625rem; padding:0; border:none\"><p class=\"p_Normal\">Setting<\/p>\n\r<\/th>\n\r<th style=\"vertical-align:top; width:31.8125rem; padding:0; border:none\"><p class=\"p_Normal\">Description<\/p>\n\r<\/th>\n\r<\/tr>\n\r<\/thead>\n\r<tbody>\n\r<tr>\n\r<td style=\"vertical-align:top; width:11.0625rem; padding:0; border:none\"><p class=\"p_Normal\">Device types<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:31.8125rem; padding:0; border:none\"><p class=\"p_Normal\">A list of device types (as defined in the <a href=\"catalog-service.html\" class=\"topiclink\">Catalog Service<\/a>). The result set will only include devices whose device type matches with one of the given device types.<\/p>\n\r<p class=\"p_Normal\">If the list is empty the result set will be empty (as no device type matches)<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/tbody>\n\r<\/table>\n\r<\/div>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Validation Rules<\/span><\/h1>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Device types list must contain at least one device type: If no device type is given this term will not match any device.<\/p><p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>All device types must be valid device types, i.e. must be device types registered in the Catalog Service. If the given device type id is not valid the results will not list any devices of that non-existing type.<\/p>"
})
