hmLoadTopic({
hmKeywords:"",
hmTitle:"Resource compositions",
hmDescription:"While display groups defined with a firmware variant version give clients a hint how to visualize the set of resource instances within that firmware variant version, resource...",
hmPrevLink:"display-groups.html",
hmNextLink:"extended-properties2.html",
hmParentLink:"catalog-service.html",
hmBreadCrumbs:"<a href=\"neutral-backend-infrastructure.html\">Neutral backend infrastructure<\/a> &gt; <a href=\"catalog-service.html\">Catalog Service<\/a>",
hmTitlePath:"Neutral backend infrastructure > Catalog Service > Resource compositions",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Resource compositions<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">While display groups defined with a firmware variant version give clients a hint how to visualize the set of resource instances within that firmware variant version, resource compositions are used to a) define equivalent resource instances across device types, firmware variants and versions and to b) define subsets of resource instances with special meaning across device types.<\/p>\n\r<p class=\"p_Normal\">Resource compositions are global catalog elements that provide a set of named composition elements. A resource instances of a firmware variant version can be linked to one composition element within a resource composition, but can be linked to any number of composition elements as long as these elements belong to different resource compositions.<\/p>\n\r<p class=\"p_Normal\">Example 1:<\/p>\n\r<p class=\"p_Normal\">A resource composition named “The Main 3” may be used to define a structure that holds the main three resource instances of firmware variant versions within specific device types. This resource composition would define three elements named 1st, 2nd and 3rd. Now within a firmware variant version one resource instance can be mapped to the element 1st, one to element 2nd one to element 3rd.<\/p>\n\r<p class=\"p_Normal\">A client software may now use this information to render the 3 most important resource instance for a specific firmware variant version.<\/p>\n\r<p class=\"p_Normal\">Example 2:<\/p>\n\r<p class=\"p_Normal\">A resource composition named “Fill state” may be used to define the resource instance that matches the meaning “Fill state” across different firmware variant versions. This resource composition would only have one element named Fill state. Within each firmware variant version one (and only one) resource instance can now be mapped to the fill stat element.<\/p>\n\r<p class=\"p_Normal\">Client software can now use this information to render the fill state for different device types.<\/p>\n\r"
})
