hmLoadTopic({
hmKeywords:"",
hmTitle:"Latest transmission mode",
hmDescription:"Devices can transmit value on occasion (typical for mobile gateways) or as result of a trigger event like a dispense action (typical for devices connected to stationary...",
hmPrevLink:"resource-instance-value2.html",
hmNextLink:"falsification.html",
hmParentLink:"device-filter-term-types.html",
hmBreadCrumbs:"<a href=\"backend-infrastructure.html\">Backend infrastructure<\/a> &gt; <a href=\"client-service.html\">Client Service<\/a> &gt; <a href=\"device-filter.html\">Device filter<\/a> &gt; <a href=\"device-filter-term-types.html\">Device filter term types<\/a>",
hmTitlePath:"Backend infrastructure > Client Service > Device filter > Device filter term types > Latest transmission mode",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Latest transmission mode<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Devices can transmit value on occasion (typical for mobile gateways) or as result of a trigger event like a dispense action (typical for devices connected to stationary gateways). This transmission mode <\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Gateway type.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">This term filters for the transmission mode of the latest resource instance value reported. I.e. checks the latest reported value for each resource instance of the device and if one of those matches the defined transmission mode the device will match this term. <\/p>\n\r<p class=\"p_Normal\">If the a<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Settings<\/span><\/h1>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0.3750rem 0;\"><table style=\"border:none; border-spacing:0;\">\n\r<thead>\n\r<tr>\n\r<th style=\"vertical-align:top; width:11.0625rem; padding:0; border:none\"><p class=\"p_Normal\">Setting<\/p>\n\r<\/th>\n\r<th style=\"vertical-align:top; width:31.8125rem; padding:0; border:none\"><p class=\"p_Normal\">Description<\/p>\n\r<\/th>\n\r<\/tr>\n\r<\/thead>\n\r<tbody>\n\r<tr>\n\r<td style=\"vertical-align:top; width:11.0625rem; padding:0; border:none\"><p class=\"p_Normal\">Transmission mode<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:31.8125rem; padding:0; border:none\"><p class=\"p_Normal\">Triggered: latest status is recorded with triggered<\/p>\n\r<p class=\"p_Normal\">Occasional: latest status recorded with occasional<\/p>\n\r<p class=\"p_Normal\">Undefined<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:11.0625rem; padding:0; border:none\"><p class=\"p_Normal\">Maximum age<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:31.8125rem; padding:0; border:none\"><p class=\"p_Normal\">If given only devices that have a latest resource instance value with the defined transmission modes within the given time span will match the term.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/tbody>\n\r<\/table>\n\r<\/div>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Time criteria<\/span><\/h1>\n\r<p class=\"p_Normal\">Maximum age of last resource instance update given as time span.<\/p>\n\r"
})
