hmLoadTopic({
hmKeywords:"",
hmTitle:"Version 3",
hmDescription:"Length: Fixed length 13 characters Characters Content 1 - 6 Production date: Date when the device this component was initially part of passed the end test. Not necessarily the",
hmPrevLink:"v2.html",
hmNextLink:"device-qr-codes.html",
hmParentLink:"serial-numbers.html",
hmBreadCrumbs:"<a href=\"common.html\">Common<\/a> &gt; <a href=\"serial-numbers.html\">Serial Numbers<\/a>",
hmTitlePath:"Common > Serial Numbers > Version 3",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Version 3<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Length: Fixed length 13 characters<\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0.3750rem 0;\"><table style=\"border:none; border-spacing:0;\">\n\r<thead>\n\r<tr>\n\r<th style=\"vertical-align:top; width:6.0000rem; height:1.5000rem; padding:0; border:none\"><p class=\"p_Normal\">Characters<\/p>\n\r<\/th>\n\r<th style=\"vertical-align:top; width:27.8750rem; height:1.5000rem; padding:0; border:none\"><p class=\"p_Normal\">Content<\/p>\n\r<\/th>\n\r<\/tr>\n\r<\/thead>\n\r<tbody>\n\r<tr>\n\r<td style=\"vertical-align:top; width:6.0000rem; padding:0; border:none\"><p class=\"p_Normal\">1 - 6<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:27.8750rem; padding:0; border:none\"><p class=\"p_Normal\">Production date: Date when the device this component was initially part of passed the end test. Not necessarily the same as the Birth Date recorded in the device\'s digital twin.<\/p>\n\r<p class=\"p_Normal\">Date is given in format <span class=\"f_InlineCode\">yyMMdd<\/span> i.e. 2 digit year, 2 digit month, two digit day<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:6.0000rem; padding:0; border:none\"><p class=\"p_Normal\">7 - 9<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:27.8750rem; padding:0; border:none\"><p class=\"p_Normal\">Production line: Identifier of the production line that produced the device the component was initially part of. Formatted as base 36 cipher<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:6.0000rem; padding:0; border:none\"><p class=\"p_Normal\">10 - 13<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:27.8750rem; padding:0; border:none\"><p class=\"p_Normal\">Sequential number defined during the end-test. Formatted as base 36 cipher<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/tbody>\n\r<\/table>\n\r<\/div>\n\r"
})
