hmLoadTopic({
hmKeywords:"",
hmTitle:"Visibility",
hmDescription:"Some information managed in the Catalog Service is marked with a visibility attribute. This visibility attribute is a hint to other systems using the Catalog Service...",
hmPrevLink:"catalog-element-description.html",
hmNextLink:"digital-twin-service.html",
hmParentLink:"catalog-service.html",
hmBreadCrumbs:"<a href=\"neutral-backend-infrastructure.html\">Neutral backend infrastructure<\/a> &gt; <a href=\"catalog-service.html\">Catalog Service<\/a>",
hmTitlePath:"Neutral backend infrastructure > Catalog Service > Visibility",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Visibility<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Some information managed in the Catalog Service is marked with a visibility attribute. This visibility attribute is a hint to other systems using the Catalog Service dynamically adapt user interfaces according to the role the accessing user has. <\/p>\n\r<p class=\"p_Normal\">The Catalog Service does not enforce this visibility in any way, it is up to the systems using the Catalog Service to implement the visibility accordingly.<\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0.3750rem 0;\"><table style=\"width:100%; border:none; border-spacing:0; border-collapse:collapse;\">\n\r<thead>\n\r<tr>\n\r<th style=\"vertical-align:top; width:11.4375rem; background-color:#DCDCDC; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Visibility<\/p>\n\r<\/th>\n\r<th style=\"vertical-align:top; width:36.5000rem; background-color:#DCDCDC; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Description<\/p>\n\r<\/th>\n\r<\/tr>\n\r<\/thead>\n\r<tbody>\n\r<tr>\n\r<td style=\"vertical-align:top; width:11.4375rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Everyone<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:36.5000rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">An element with this visibility shall be shown to every user of the HsM system.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:11.4375rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Maintenance<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:36.5000rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">An element with this visibility shall only be shown to users in the HsM system that care about maintenance of devices.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:11.4375rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">HsM Administator<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:36.5000rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">An element with visibility shall only be shown to users who administrator the HsM system instance of an HsM OEM Partner<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; width:11.4375rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">Developer<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; width:36.5000rem; padding:0; border:solid thin #c0c0c0;\"><p class=\"p_Normal\">only shown to developers of the HsM system.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/tbody>\n\r<\/table>\n\r<\/div>\n\r"
})
