pageinfo = [[1624469740,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469743,0,0,0,null],
	[1624469743,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469743,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469743,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469743,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469743,0,0,0,null],
	[1624469740,0,0,0,null],
	[1624469743,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469742,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469739,0,0,0,null],
	[1624469741,0,0,0,null],
	[1624469738,0,0,0,null],
	[1624469743,0,0,0,null],
	[1624469741,0,0,0,null]];
pagedata = [ ["./administrators-guide.html","Administrator&#39;s Guide","Installation Maintenance",""],
["./administrators-guide2.html","Administrator&#39;s Guide","Enter topic text here.",""],
["./administrators-guide_2.html","Administrator&#39;s Guide","Installation Maintenance",""],
["./article-numbers.html","Article numbers","Enter topic text here.",""],
["./authentication-and-authorizato.html","Authentication","The HsM Catalog Service Browse API allows anonymous access to all its endpoints. To get data from these browse endpoints the client however has to...",""],
["./authorization.html","Authorization","The entities managed through the Catalog Service’s Admin API are protected using policies",""],
["./autzorization-and-uthenticatio.html","Authorization and Authentication","Enter topic text here.",""],
["./backend-infrastructure.html","Backend infrastructure","Enter topic text here.",""],
["./catalog-element-description.html","Catalog Element Description","For many entities managed in the Catalog Service the Catalog Service stores descriptive information in form of catalog element descriptions. A cat...",""],
["./catalog-service.html","Catalog Service","The HsM Catalog Service provides meta data about all HsM device types. This meta data is used in many areas of HsM to dynamically adapt to new dev...",""],
["./client-service.html","Client Service","Enter topic text here.",""],
["./combining-devices.html","Combining devices","Compound devices can either be created by the Digital Twin registration agent when the device is first registered, or they can be created through ...",""],
["./command-line-start.html","Running from command line","...exe --environemnt=dev",""],
["./common.html","Common","Enter topic text here.",""],
["./compound-device-status.html","Compound device status","Compound devices are part of the base set of devices to which device filters are applied. The Combined device filter term can be used to restrict ...",""],
["./compound-device-types.html","Compound device types","nh  HsM supports the concept of compound devices, i.e. devices can include other devices. These devices within other devices, however, are mo...",""],
["./compound-devices.html","Compound devices","The Digital Twin Service supports compound device types. It records the current relationship between devices and keeps a history of relationships ...",""],
["./configuration-app.html","Configuration app","Enter topic text here.",""],
["./configuration-files.html","Configuration files","{ \"Logging\": { \"NLog\": { \"IncludeScopes\": false, \"ParseMessageTemplates\": true, \"CaptureMessageProper...",""],
["./configuration.html","Configuration","For running the Digital Twin Registration Agent a working directory and an environment name must be specified. The root working directory for all ...",""],
["./data-analysis-service.html","Data Analysis Service","Enter topic text here.",""],
["./data-link-monitoring-protocol.html","Data link monitoring protocol","For reporting the status of non-gateway devices to the backend the stationary gateway shall use a simple protocol.",""],
["./data-link-monitoring-service-d.html","Data link monitoring service database","Data volume estimation Table: StationaryGatewayOnlineStatus 2E4 stationary gateways 100 bytes / record (rough estimation including page headers, i...",""],
["./data-link-monitoring-service-l.html","Data link monitoring service logic","The data link monitoring service records the result of monitoring data links between non-gateway devices and stationary gateways and the results o...",""],
["./data-link-monitoring-service.html","Data Link Monitoring Service","HsM stationary gateways are used to connect non-gateway devices to the HsM backend permanently and therefore enable a near-real-time uplink-commun...",""],
["./data-link.html","Data link","The HsM system can also manage pure analog dispensers (with no data link to the HsM HsM Backend), this device filter term type can be used to filt...",""],
["./date-interval.html","Date interval","Enter topic text here.",""],
["./decision.html","Detect version of a HsM serial number","If length is exactly 13",""],
["./definitions.html","Definitions","device type: component type compound device type compound component",""],
["./delivering-device-types-via-th.html","Delivering device types via the browse API","When device types are requested and then delivered via the browse API their component type placeholders are resolved to component types, the accor...",""],
["./device-dates.html","Installation date","Filters for devices based on their installation date, i.e. the date when the device was installed at a specific locaiton.",""],
["./device-dates_2.html","Birth date","Filters by birth date of the device (or to be exact by the birth date of the digital twin)",""],
["./device-filter-term-types.html","Device filter term types","Device filter term types are predefined building blocks for device filters. Term types can have settings and have their own validation rules.",""],
["./device-filter.html","Device filter","A device filter is a logical expression that can be applied to the devices managed by the Client Service to filter for a subset of these devices.",""],
["./device-provisioning-registrati.html","Device Provisioning Registration Agent","Flow:  * Start process every X hours at timestamp t * Get all stationary gateway devices from Provider DB, born after t - X - delta   De...",""],
["./device-provisioning-service.html","Device Provisioning Service","HsM uses an Azure Device Provisioning service for Stationary gateways so that these gateways will initially connect to the right HsM OeM Partner&#39;s...",""],
["./device-qr-codes.html","HsMDevice QR Codes","Some HsM device components have stickers on them with a QR code that carries information about device the component belongs to (at the time of pro...",""],
["./device-type.html","Device type","Filters for devices that are of one of the given device types.",""],
["./digital-twin-lifecycle-status.html","Digital Twin lifecycle status","The Digital Twin Service keep track of the life-cycle status of devices.",""],
["./digital-twin-registration-agen.html","Digital Twin Registration Agent","Enter topic text here.",""],
["./digital-twin-service.html","Digital Twin Service","The HsM Digital Twin Service is part of the HsM neutral backend. It is the place where digital twins for each produced HsM device are initially re...",""],
["./display-groups.html","Display Groups","The display groups defined with a firmware variant version are a partition of the set of resource instances defined with that firmware variant ver...",""],
["./display-groups2.html","Resource compositions","While display groups defined with a firmware variant version give clients a hint how to visualize the set of resource instances within that firmwa...",""],
["./enumerating-resource-instances.html","Enumerating resource instances","Since compound device types can contain multiple compound member device types, they can also contain multiple firmware types. Therefore the possib...",""],
["./environment-setting.html","Environment setting","Please enable JavaScript to view this site. ",""],
["./environment-variable-dtra_conf.html","Environment variable DTRA_CONFIG_DIR","The Windows System Environment Variable DTRA_CONFIG_DIR defines the directory where configuration files are expected and where the Digital Twin Re...",""],
["./execution-scope.html","Execution Scope","When a device filter is executed, it is always executed in a specific scope. This execution scope defines the base set of devices to which the fil...",""],
["./extended-properties.html","Extended Properties","The Catalog Service can define extended properties for each device type. The Digital Twin Service is the place where the values for these extended...",""],
["./extended-properties2.html","Extended Properties","Each device type can have definitions for extended properties. Extended properties are properties of devices that are instance of a defined device...",""],
["./falsification.html","Falsification","This term filters is mostly used internally. No device will ever pass instances of this term type.",""],
["./frontends.html","Frontends","Enter topic text here.",""],
["./gateway-devices.html","Gateway devices","In HsM stationary gateways are also handled as HsM devices therefore those gateways also have a data-link status.",""],
["./handling-of-invalid-device-filters.html","Handling of invalid device filters","Device filters may be invalid due to various reasons (see below).The Client Service will handle invalid device filters gracefully, i.e. the execut...",""],
["./hsm-oem-customers.html","HsM OEM Customers","Entities in the Catalog Service are mapped to one or more OEM Customers. E.g. a device type is mapped to one or more OEM-Customers.",""],
["./index.html","Introduction","Enter topic text here.",""],
["./installation.html","Installation","Prerequisites .NET Core 3.1 runtime: The Digital Twin Registration Agent is a .NET Core 3.1.10 application and therefore the .NET Core 3.1 run tim...",""],
["./introduction2.html","Introduction","HsM supports the concept of compound devices, i.e. devices can include other devices. These devices within other devices, however, are more than j...",""],
["./latest-status-update.html","Latest status update","Filters for devices that sent a resource instance value (for any resource instance) within the configured time span.",""],
["./location-of-configuration-file.html","Location of configuration file","All  configuration for Digital Twin Registration Agent is done through a configuration file. ",""],
["./location-tree-filter.html","Location tree filter","Filters for devices that are installed at specific locations with in the location tree of customers.",""],
["./logging.html","Logging","For monitoring the Digital Twin Registration Agent the program logs via the nlog framework and therefore allows for versatile routing of log messa...",""],
["./logging2.html","Logging","Enter topic text here.",""],
["./logical-operators.html","Logical operators","Device filters support following logical operators:",""],
["./monitoring-data-link-between-n.html","Monitoring data link between non-gateway devices and stationary gateways","Stationary gateway actively monitor the Bluetooth communication links with non-gateway devices and report the status of this links to the Data lin...",""],
["./monitoring-data-link-between-s.html","Monitoring data link between stationary gateways and the HsM backend","The Data link monitoring service monitors the data link between stationary gateways and the HsM Backend. The technical environment allows to immed...",""],
["./neutral-backend-infrastructure.html","Neutral backend infrastructure","Enter topic text here.",""],
["./non-gateway-devices.html","Non gateway devices","The data link between a non-gateway device and the backend can be in one of the following states:",""],
["./operations-guide.html","Operations Guide","Enter topic text here.",""],
["./operations-guide2.html","Operations guide","Enter topic text here.",""],
["./operations-guide3.html","Operations guide","Enter topic text here.",""],
["./operations-guide4.html","Operations guide","The Digital Twin Registration Agent is a Windows program that is intended to be run as a Windows Service but can (for debugging and testing purpos...",""],
["./presented-data-link-status.html","Presented data link status","Non gateway de   The data link between a non-gateway device and the backend can be in one of the following states: Not connected via stationa...",""],
["./primary-data-processing.html","Primary Data Processing","HsM uses Azure IoT Hub infrastructure for device-to-cloud and cloud-to-device communication.",""],
["./problem-types.html","Problem types","Enter topic text here.",""],
["./queue.html","Queue","The queue subdirectory is used as a queue for devices that need to be registered with the Digital Twin Service. The queue directory is filled by q...",""],
["./queuing.html","Queuing","Enter topic text here.",""],
["./recording-of-data-link-status.html","Recording of data link status","The data link status of a HsM device is recorded as resource instance values for each device. I.e. the data link status of each HsM device is reco...",""],
["./removing-a-windows-service.html","Removing a Windows Service","Using PowerShell Note you need to run PowerShell with administrative privileges to modify Windows Services. Removing a Windows Service for the Dig...",""],
["./resource-instance-value2.html","Latest Resource instance value","Filters devices by their latest reported resource instance values. ",""],
["./rest-api.html","REST API","The REST API documentation of the HsM Catalog Service can be found at http://catalog.hsm.digital/swagger/index.html.",""],
["./run-as-windows-service.html","Creating a Windows Service","While there are many ways to register a program as a Windows Service, we recommend the following approach with PowerShell. Note you need to run Po...",""],
["./serial-numbers.html","Serial Numbers","Serial numbers are used to uniquely identify components of HsM devices. A device can be uniquely identified by the serial number of one of its com...",""],
["./service-app.html","Service App","Enter topic text here.",""],
["./starting-and-stopping-the-wind.html","Running as Windows service","Enter topic text here.",""],
["./term-type-availability.html","Term type availability","Some device filter terms are restricted to HsM users with specific permissions.",""],
["./time-series-storage.html","Time Series Storage","Enter topic text here.",""],
["./time-synchronization.html","Time synchronization","The Digital Twin Registration Agent uses an incremental approach when registering devices. I.e. it checks for changes in the provider DB regularly...",""],
["./transmission-mode.html","Latest transmission mode","Devices can transmit value on occasion (typical for mobile gateways) or as result of a trigger event like a dispense action (typical for devices c...",""],
["./updating.html","Updating","Updating the Digital Twin Registration Agent is done by replacing all the files int he program directory with the files of the new version - just ...",""],
["./v1.html","Version 1","Lentgh: variable 1 - 6: Date yyMMdd 7 - 9 Line (base 36 cipher) 10 - 13: Sequential Number (base 36 cipher)",""],
["./v2.html","Version 2","Product Type coe  2005-200916-00202",""],
["./v3.html","Version 3","Length: Fixed length 13 characters Characters Content 1 - 6 Production date: Date when the device this component was initially part of passed the ...",""],
["./validating-device-filters.html","Validating device filters","The Client Service provides the possibility to validate a device filter and report the result so this validation in a human readable way. This val...",""],
["./visibility.html","Visibility","Some information managed in the Catalog Service is marked with a visibility attribute. This visibility attribute is a hint to other systems using ...",""],
["./web-portal.html","Web portal","Enter topic text here.",""],
["./wording.html","Wording","Wording in Catalog: Compound device type: Device type with at least one device type placeholder. Compound member device type: Device type that can...",""],
["./working-directory.html","Working directory","The DTRA will create a working directory within the configured  DTRA_CONFIG_DIR the name of the working directory will be data.&#60;environmen...",""],
["./xibu-app.html","Xibu App","Enter topic text here.",""]];
