pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./administrators-guide.html","Administrator&#39;s Guide","Administrator&#39;s Guide Top Previous Next Installation Maintenance ",""],
["./administrators-guide2.html","Administrator&#39;s Guide","Administrator&#39;s Guide Top Previous Next Enter topic text here. ",""],
["./administrators-guide_2.html","Administrator&#39;s Guide","Administrator&#39;s Guide Top Previous Next Installation Maintenance ",""],
["./article-numbers.html","Article numbers","Article numbers Top Previous Enter topic text here. ",""],
["./authentication-and-authorizato.html","Authentication","Authentication Top Previous Next The HsM Catalog Service Browse API allows anonymous access to all its endpoints. To get data from these browse en...",""],
["./authorization.html","Authorization","Authorization Top Previous Next The entities managed through the Catalog Service’s Admin API are protected using policies DeviceType.Write: Write ...",""],
["./autzorization-and-uthenticatio.html","Authorization and Authentication","Authorization and Authentication Top Previous Next Enter topic text here. ",""],
["./backend-infrastructure.html","Backend infrastructure","Backend infrastructure Top Previous Next Enter topic text here. ",""],
["./catalog-element-description.html","Catalog Element Description","Catalog Element Description Top Previous Next For many entities managed in the Catalog Service the Catalog Service stores descriptive information ...",""],
["./catalog-service.html","Catalog Service","Catalog Service Top Previous Next The HsM Catalog Service provides meta data about all HsM device types. This meta data is used in many areas of H...",""],
["./client-service.html","Client Service","Client Service Top Previous Next Enter topic text here. ",""],
["./combining-devices.html","Combining devices","Combining devices Top Previous Next Compound devices can either be created by the Digital Twin registration agent when the device is first registe...",""],
["./command-line-start.html","Running from command line","Running from command line Top ...exe --environemnt=dev ",""],
["./common.html","Common","Common Top Previous Next Enter topic text here. ",""],
["./compound-device-status.html","Compound device status","Compound device status Top Previous Next Compound devices are part of the base set of devices to which device filters are applied. The Combined de...",""],
["./compound-device-types.html","Compound device types","Compound device types Top Previous Next nh HsM supports the concept of compound devices, i.e. devices can include other devices. These devices wit...",""],
["./compound-devices.html","Compound devices","Compound devices Top Previous Next The Digital Twin Service supports compound device types . It records the current relationship between devices a...",""],
["./configuration-app-preshared-ke.html","Configuration app preshared key authentication","Configuration app preshared key authentication Top Previous Next Enter topic text here. ",""],
["./configuration-app.html","Configuration app","Configuration app Top Previous Next Enter topic text here. ",""],
["./configuration-files.html","Configuration files","Configuration files Top { \"Logging\": { \"NLog\": { \"IncludeScopes\": false, \"ParseMessageTemplates\": true, \"CaptureMessageProperties\": true }, \"LogLe...",""],
["./configuration.html","Configuration","Configuration Top For running the Digital Twin Registration Agent a working directory and an environment name must be specified. The root working ...",""],
["./data-analysis-service.html","Data Analysis Service","Data Analysis Service Top Previous Next Enter topic text here. ",""],
["./data-link-monitoring-protocol.html","Data link monitoring protocol","Data link monitoring protocol Top Previous Next For reporting the status of non-gateway devices to the backend the stationary gateway shall use a ...",""],
["./data-link-monitoring-service-d.html","Data link monitoring service database","Data link monitoring service database Top Previous Next Data volume estimation Table: StationaryGatewayOnlineStatus 2E4 stationary gateways 100 by...",""],
["./data-link-monitoring-service-l.html","Data link monitoring service logic","Data link monitoring service logic Top Previous Next The data link monitoring service records the result of monitoring data links between non-gate...",""],
["./data-link-monitoring-service.html","Data Link Monitoring Service","Data Link Monitoring Service Top Previous Next HsM stationary gateways are used to connect non-gateway devices to the HsM backend permanently and ...",""],
["./data-link.html","Data link","Data link capability Top Previous Next The HsM system can also manage pure analog dispensers (with no data link to the HsM HsM Backend), this devi...",""],
["./date-interval.html","Date interval","Date interval Top Previous Next Enter topic text here. ",""],
["./decision.html","Detect version of a HsM serial number","Detect version of a HsM serial number Top Previous Next If length is exactly 13 ",""],
["./definitions.html","Definitions","Definitions Top Previous Next device type: component type compound device type compound component ",""],
["./delivering-device-types-via-th.html","Delivering device types via the browse API","Delivering device types via the browse API Top Previous Next When device types are requested and then delivered via the browse API their component...",""],
["./developer-documentation.html","Developer documentation","Developer documentation Top Previous Next Enter topic text here. ",""],
["./device-dates.html","Installation date","Installation date Top Previous Next Filters for devices based on their installation date, i.e. the date when the device was installed at a specifi...",""],
["./device-dates_2.html","Birth date","Birth date Top Previous Next Filters by birth date of the device (or to be exact by the birth date of the digital twin) Settings Setting Descripti...",""],
["./device-filter-term-types.html","Device filter term types","Device filter term types Top Previous Next Device filter term types are predefined building blocks for device filters. Term types can have setting...",""],
["./device-filter.html","Device filter","Device filter Top Previous Next A device filter is a logical expression that can be applied to the devices managed by the Client Service to filter...",""],
["./device-provisioning-registrati.html","Device Provisioning Registration Agent","Device Provisioning Registration Agent Top Flow: * Start process every X hours at timestamp t * Get all stationary gateway devices from Provider D...",""],
["./device-provisioning-service.html","Device Provisioning Service","Device Provisioning Service Top Previous Next HsM uses an Azure Device Provisioning service for Stationary gateways so that these gateways will in...",""],
["./device-qr-codes.html","HsMDevice QR Codes","HsMDevice QR Codes Top Previous Next Some HsM device components have stickers on them with a QR code that carries information about device the com...",""],
["./device-type.html","Device type","Device type Top Previous Next Filters for devices that are of one of the given device types. Settings Setting Description Device types A list of d...",""],
["./digital-twin-lifecycle-status.html","Digital Twin lifecycle status","Digital Twin lifecycle status Top Previous Next The Digital Twin Service keep track of the life-cycle status of devices. Status Allows transition ...",""],
["./digital-twin-registration-agen.html","Digital Twin Registration Agent","Digital Twin Registration Agent Top Enter topic text here. ",""],
["./digital-twin-service.html","Digital Twin Service","Digital Twin Service Top Previous Next The HsM Digital Twin Service is part of the HsM neutral backend. It is the place where digital twins for ea...",""],
["./digital-twin-service2.html","Digital Twin Service","Digital Twin Service Top Previous Next Enter topic text here. ",""],
["./display-groups.html","Display Groups","Display Groups Top Previous Next The display groups defined with a firmware variant version are a partition of the set of resource instances defin...",""],
["./display-groups2.html","Resource compositions","Resource compositions Top Previous Next While display groups defined with a firmware variant version give clients a hint how to visualize the set ...",""],
["./enumerating-resource-instances.html","Enumerating resource instances","Enumerating resource instances Top Previous Next Since compound device types can contain multiple compound member device types, they can also cont...",""],
["./environment-setting.html","Environment setting","Environment setting Top ",""],
["./environment-variable-dtra_conf.html","Environment variable DTRA_CONFIG_DIR","Environment variable DTRA_CONFIG_DIR Top The Windows System Environment Variable DTRA_CONFIG_DIR defines the directory where configuration files a...",""],
["./execution-scope.html","Execution Scope","Execution Scope Top Previous Next When a device filter is executed, it is always executed in a specific scope. This execution scope defines the ba...",""],
["./extended-properties.html","Extended Properties","Extended Properties Top Previous Next The Catalog Service can define extended properties for each device type. The Digital Twin Service is the pla...",""],
["./extended-properties2.html","Extended Properties","Extended Properties Top Previous Next Each device type can have definitions for extended properties. Extended properties are properties of devices...",""],
["./falsification.html","Falsification","Falsification Top Previous Next This term filters is mostly used internally. No device will ever pass instances of this term type. Settings None. ...",""],
["./frontends.html","Frontends","Frontends Top Previous Next Enter topic text here. ",""],
["./gateway-devices.html","Gateway devices","Gateway devices Top Previous Next In HsM stationary gateways are also handled as HsM devices therefore those gateways also have a data-link status...",""],
["./handling-of-invalid-device-filters.html","Handling of invalid device filters","Handling of invalid device filters Top Previous Next Device filters may be invalid due to various reasons (see below).The Client Service will hand...",""],
["./hsm-oem-customers.html","HsM OEM Customers","HsM OEM Customers Top Previous Next Entities in the Catalog Service are mapped to one or more OEM Customers. E.g. a device type is mapped to one o...",""],
["./installation.html","Installation","Installation Top Prerequisites .NET Core 3.1 runtime: The Digital Twin Registration Agent is a .NET Core 3.1.10 application and therefore the .NET...",""],
["./introduction.html","Introduction","Introduction Top Next Enter topic text here. ",""],
["./introduction2.html","Introduction","Introduction Top Previous Next HsM supports the concept of compound devices, i.e. devices can include other devices. These devices within other de...",""],
["./latest-status-update.html","Latest status update","Latest status update Top Previous Next Filters for devices that sent a resource instance value (for any resource instance) within the configured t...",""],
["./life-cycle-state.html","Life cycle state","Life cycle state Top Previous Next Digital twins reflect the physical devices&#39; life cycle state. State Description Can be transitioned to Inactive...",""],
["./location-of-configuration-file.html","Location of configuration file","Location of configuration file Top All configuration for Digital Twin Registration Agent is done through a configuration file. Which configuration...",""],
["./location-tree-filter.html","Location tree filter","Location tree filter Top Previous Next Filters for devices that are installed at specific locations with in the location tree of customers. Settin...",""],
["./logging.html","Logging","Logging Top For monitoring the Digital Twin Registration Agent the program logs via the nlog framework and therefore allows for versatile routing ...",""],
["./logging2.html","Logging","Logging Top Enter topic text here. ",""],
["./logical-operators.html","Logical operators","Logical operators Top Previous Next Device filters support following logical operators: AND: Joins two or more device filter terms or logical oper...",""],
["./monitoring-data-link-between-n.html","Monitoring data link between non-gateway devices and stationary gateways","Monitoring data link between non-gateway devices and stationary gateways Top Previous Next Stationary gateway actively monitor the Bluetooth commu...",""],
["./monitoring-data-link-between-s.html","Monitoring data link between stationary gateways and the HsM backend","Monitoring data link between stationary gateways and the HsM backend Top Previous Next The Data link monitoring service monitors the data link bet...",""],
["./neutral-backend-infrastructure.html","Neutral backend infrastructure","Neutral backend infrastructure Top Previous Next Enter topic text here. ",""],
["./non-gateway-devices.html","Non gateway devices","Non gateway devices Top Previous Next The data link between a non-gateway device and the backend can be in one of the following states: 1.Not conn...",""],
["./operations-guide.html","Operations Guide","Operations Guide Top Previous Next Enter topic text here. ",""],
["./operations-guide2.html","Operations guide","Operations guide Top Previous Next Enter topic text here. ",""],
["./operations-guide3.html","Operations guide","Operations guide Top Previous Next Enter topic text here. ",""],
["./operations-guide4.html","Operations guide","Operations guide Top The Digital Twin Registration Agent is a Windows program that is intended to be run as a Windows Service but can (for debuggi...",""],
["./presented-data-link-status.html","Presented data link status","Presented data link status Top Previous Next Non gateway de The data link between a non-gateway device and the backend can be in one of the follow...",""],
["./primary-data-processing.html","Primary Data Processing","Primary Data Processing Top Previous Next HsM uses Azure IoT Hub infrastructure for device-to-cloud and cloud-to-device communication. Gateways mu...",""],
["./problem-types.html","Problem types","Problem types Top Previous Next Enter topic text here. ",""],
["./queue.html","Queue","Queue Top The queue subdirectory is used as a queue for devices that need to be registered with the Digital Twin Service. The queue directory is f...",""],
["./queuing.html","Queuing","Queuing Top Enter topic text here. ",""],
["./recording-of-data-link-status.html","Recording of data link status","Recording of data link status Top Previous Next The data link status of a HsM device is recorded as resource instance values for each device. I.e....",""],
["./removing-a-windows-service.html","Removing a Windows Service","Removing a Windows Service Top Using PowerShell Note you need to run PowerShell with administrative privileges to modify Windows Services. Removin...",""],
["./resource-instance-value2.html","Latest Resource instance value","Latest Resource instance value Top Previous Next Filters devices by their latest reported resource instance values. A resource instance is specifi...",""],
["./rest-api.html","REST API","REST API Top Previous Next The REST API documentation of the HsM Catalog Service can be found at http://catalog.hsm.digital/swagger/index.html . ",""],
["./run-as-windows-service.html","Creating a Windows Service","Creating a Windows Service Top While there are many ways to register a program as a Windows Service, we recommend the following approach with Powe...",""],
["./serial-numbers.html","Serial Numbers","Serial Numbers Top Previous Next Serial numbers are used to uniquely identify components of HsM devices. A device can be uniquely identified by th...",""],
["./service-app.html","Service App","Service App Top Previous Next Enter topic text here. ",""],
["./starting-and-stopping-the-wind.html","Running as Windows service","Running as Windows service Top Enter topic text here. ",""],
["./swagger-access.html","Swagger access","Swagger access Top Previous Next Enter topic text here. ",""],
["./term-type-availability.html","Term type availability","Term type availability Top Previous Next Some device filter terms are restricted to HsM users with specific permissions. ",""],
["./time-series-storage.html","Time Series Storage","Time Series Storage Top Previous Next Enter topic text here. ",""],
["./time-synchronization.html","Time synchronization","Time synchronization Top The Digital Twin Registration Agent uses an incremental approach when registering devices. I.e. it checks for changes in ...",""],
["./transmission-mode.html","Latest transmission mode","Latest transmission mode Top Previous Next Devices can transmit value on occasion (typical for mobile gateways) or as result of a trigger event li...",""],
["./updating.html","Updating","Updating Top Updating the Digital Twin Registration Agent is done by replacing all the files int he program directory with the files of the new ve...",""],
["./v1.html","Version 1","Version 1 Top Previous Next Lentgh: variable 1 - 6: Date yyMMdd 7 - 9 Line (base 36 cipher) 10 - 13: Sequential Number (base 36 cipher) ",""],
["./v2.html","Version 2","Version 2 Top Previous Next Product Type coe 2005-200916-00202 ",""],
["./v3.html","Version 3","Version 3 Top Previous Next Length: Fixed length 13 characters Characters Content 1 - 6 Production date: Date when the device this component was i...",""],
["./validating-device-filters.html","Validating device filters","Validating device filters Top Previous Next The Client Service provides the possibility to validate a device filter and report the result so this ...",""],
["./visibility.html","Visibility","Visibility Top Previous Next Some information managed in the Catalog Service is marked with a visibility attribute. This visibility attribute is a...",""],
["./web-portal.html","Web portal","Web portal Top Previous Next Enter topic text here. ",""],
["./wording.html","Wording","Wording Top Previous Next Wording in Catalog: Compound device type: Device type with at least one device type placeholder. Compound member device ...",""],
["./working-directory.html","Working directory","Working directory Top The DTRA will create a working directory within the configured DTRA_CONFIG_DIR the name of the working directory will be dat...",""],
["./xibu-app.html","Xibu App","Xibu App Top Previous Next Enter topic text here. ",""]];
